# Generated by Django 4.2.2 on 2023-06-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
