# Generated by Django 4.2.2 on 2023-07-14 22:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
